# Generated by Django 4.0.5 on 2022-08-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Troubleshootapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='id',
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
