# Generated by Django 4.0.5 on 2022-07-28 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Troubleshootapp', '0002_alter_users_user_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
            ],
        ),
    ]
