# Generated by Django 4.0.5 on 2022-07-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Troubleshootapp', '0004_alter_users_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
            ],
        ),
    ]
